### ISSUE TITLE
Milestone 7: Requirements

### ISSUE THREAD

**Issue by gsufrank** [GSCSCI5530/Angstrom#7]
(Due Sep. 20)

Grading: Team

This will be the main requirements document for your project. If you were charging the client for your work, this document would form part of that contract, specifying exactly what features your software will implement. The other part of the contract would be the payment details.

The document includes the detailed design you made before (so, embed or add links to those pngs) but extends on that with detailed descriptions of all the desired features. Try to list them roughly in the order in which they will be implemented. Also, if your client has different preferences over features (some are much more important than others, which might not get implemented) then mark the features accordingly.

Your requirements document will usually contain a few items that are beyond the scope of this class. That is, these are features I do not expect you to implement for this class.

For example, if you are building an email app, you might have:

user can login
download user's email to app
display emails on main screen in list view, see Design Image #1 (you link to it)
compose email (DI #2 link)
send email functionality (talk to SMTP server)
CRUD contacts (DI #3 link)
download contacts from server and show in contacts screen
app looks good on phones
displays all messages even when offline
and so on..
The requirements might evolve slightly as you make decisions as to what works for your app. However, make sure that the requirements documents stays up to date with the current development plan.

The items on this list are also close to the programming Issue items you will be adding to your GitHub Issues, and assigning to team members. For example, item 1 can become its own issue: "Add login screen" along with a "Log user into IMAP server". Item 2 then becomes "Download emails from IMAP server" and "Store emails in local SQLite database". Every week or so, you will look at the next requirement(s) that need to get done, break them down into programming Issues, create then on GitHub, assign to a team member. Repeat.

After the full list of requirements is done, you will then decide on the set of features you will implement for your Prototype milestone, due at the end of the semester. You will also create one GitHub Issue, with label:enhancement milestone:Prototype, for each feature you plan to implement by the end of the semester. Since this is a prototype implementation (we are seeing if we can use the technologies), some of your Issues might describe which technology you will be using, others will be standard issues described from the user's perspective. For example, for the email app above you might have issues such as:

Deploy to Google App Engine. Using their Java framework.
Users can login.
Use the App Engine Mail API to send a message, and to receive a message.
Displays received email to user.
User can enter some text and then send it as an email.
Integrate Bootstrap into login and email pages.
Store message text in google cloud datastore
Deliverables
Make a Requirements wiki page and list your requirements there.
Each item should succinctly explain a small feature, or part of it.
Each one will have a number. You can add sub-numbering, 1.1, 1.2, 1.2.1, etc. if you want.
Add all the proof-of-concept Issues to your GitHub Issues with label:enhancement, milestone:Prototype. These are what you will implement by the end of this semester. We will discuss these in our next meeting and come to an agreement (I might add/delete some of them).
Checklist: formatted for easy cut-n-paste to a GitHub Issue.

- [ ] Create Requirements page
- [ ] All features are numbered
- [ ] All the major features required by the client are covered in the list.
- [ ] The order roughly matches the preferences of the client, or features have been otherwise marked to reflect preferences.
- [ ] Features are described in enough detail so as to be unambiguous.
- [ ] All the proof-of-concept issues have been added to Issues and associated with proof-of-concept milestone.
- [ ] Detailed Design images are linked or embedded in the wiki page, and hosted at github.
- [ ] The wiki page is easy to read.
